"""Added msblog published boolean for having unpublished blog posts

Revision ID: 2075faea1cbb
Revises: f3358e7c1d08
Create Date: 2021-02-02 16:06:07.923337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2075faea1cbb'
down_revision = 'f3358e7c1d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('msblog_posts', sa.Column('published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('msblog_posts', 'published')
    # ### end Alembic commands ###
