"""Set validated to nullable=False

Revision ID: 9b5b576a382a
Revises: e230e04e1b99
Create Date: 2021-02-27 00:17:56.645896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5b576a382a'
down_revision = 'e230e04e1b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # We default ot validated=True for all users, since that will maintain behavior when migrating.
    # Users previously acted like validated users, so existing users should be considered validated.
    users = sa.table('users', sa.column('validated'))
    op.execute(users.update().values(validated=True))
    op.alter_column('users', 'validated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'validated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
