"""Added validate field

Revision ID: e230e04e1b99
Revises: 2075faea1cbb
Create Date: 2021-02-16 23:03:37.202188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e230e04e1b99'
down_revision = '2075faea1cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('validated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'validated')
    # ### end Alembic commands ###
